version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: develop
  reviewers:
  - gep13
  assignees:
  - gep13
  labels:
  - dependabot
